version: '3'
services:

  streaming-server:
    image: streaming-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STREAM_KEY=bla
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./etc/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./lua-resty-openidc:/usr/local/openresty/lualib/resty/openidc:cached